### ISSUE TITLE
Documentation include "user images"

### ISSUE THREAD

**Issue by WalterMoar** [bcgov/common-hosted-form-service-techdocs#2]
The documentation in the Wiki allowed editors to paste images from screenshots, etc. This resulted in the images being uploaded to https://user-images.githubusercontent.com. We need to move all these images in this repo.

## Definition of Done:
- [x] Come up with a logical naming convention / filesystem structure for images and add it to the Style Guide
- [x] All images in the documentation are stored in `/docs/images`, possibly within a tree file structure
- [x] Check for any other content (other than YouTube videos) that may be hosted outside the documentation

**Comment by vijaivir** [comment]
The images and videos have been migrated.
