### ISSUE TITLE
Suggesting a new wiki page for using the 'OrgBook' Component - for the examples wiki page.

### ISSUE THREAD

**Issue by Stephan-McColm** [bcgov/common-hosted-form-service-techdocs#27]
I'd like to propose adding an example to your existing [CHEFS Wiki article](https://github.com/bcgov/common-hosted-form-service/wiki/Examples-of-CHEFS-forms-and-features). 

The unity team has created a template for how to extract the organization number from the the "Business Name Search Component" component, A.K.A. the "orgbook".

[Here is the JSON file for our sample form.](https://github.com/bcgov/common-hosted-form-service-techdocs/files/15045457/orgbook.json)

This solution is elegant and non-obvious. It would be helpful to the broader community.
![image](https://github.com/bcgov/common-hosted-form-service-techdocs/assets/143556068/dca3e364-ef7e-42bd-9b76-1a303a5074ba)

**Comment by bhuvan-aot** [comment]
Existing Business name search example form has been added to https://github.com/bcgov/common-hosted-form-service-techdocs/blob/main/docs/Components/Examples.md.
